apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-browser
  template:
    metadata:
      labels:
        app: web-browser
    spec:
      containers:
        - name: web-browser
          image: jlesage/firefox
          # 🔥 Resource control (VERY IMPORTANT)
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "500m"

          # ⚡ Performance tuning
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: DISPLAY_WIDTH
              value: "1024"
            - name: DISPLAY_HEIGHT
              value: "768"
            - name: KEEP_APP_RUNNING
              value: "1"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: WEB_AUTHENTICATION_USERNAME
              valueFrom:
                secretKeyRef:
                  name: browser-auth
                  key: USERNAME

            - name: WEB_AUTHENTICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: browser-auth
                  key: PASSWORD
          ports:
            - containerPort: 5800
